### ISSUE TITLE
Compare Mitsuba's "inbuilt" timers to current in-script timing

### ISSUE THREAD

**Issue by andrewgait** [UoMResearchIT/mitsuba3-manchester#14]
The [draft paper](https://github.com/UoMResearchIT/RTP-215-Photon-Propagation-Issue-Only/blob/development/ReportsAndPapers/Davis_etal_2309.12496v1.pdf) says that it uses Mitsuba's own in-built timing reports (see the end of Section 5).  From a quick search, it seems as though these methods are performed directly in the C++ code, so investigate whether these give different results to the current timing measurements in Python (plausibly, the interface from Python -> C++ could have some effect on timing measurements).

@gersabec @cofitzpa do you have the data used to create the current figures 7 and 8 in the draft paper? I can see that Keith may have done some of these measurements from some of the bash scripts in the MitsubaMPhys repository, but on a rudimentary glance through them it looks to me like that only measures the rendering time rather than the whole run time.

**Comment by andrewgait** [comment]
It's possible that the "inbuilt timers" described in the paper are actually the times from the DrJit logging as described [in this comment](https://github.com/UoMResearchIT/RTP-215-Photon-Propagation-Issue-Only/issues/36#issuecomment-2460351947).  It would still be helpful to see the data used to create the timing figures in the draft paper if this is still available.

**Comment by andrewgait** [comment]
> [@gersabec](https://github.com/gersabec) [@cofitzpa](https://github.com/cofitzpa) do you have the data used to create the current figures 7 and 8 in the draft paper? I can see that Keith may have done some of these measurements from some of the bash scripts in the MitsubaMPhys repository, but on a rudimentary glance through them it looks to me like that only measures the rendering time rather than the whole run time.

On a more thorough search through the MistubaMPhys repository, it does contain this [Jupyter notebook](https://github.com/gersabec/MitsubaMphys/blob/main/final_simulation/timing/analysis/jupyter_analysis.ipynb) which perhaps indicates that some "code generation" timings were obtained, but it's not clear from any of the other scripts how this was done.  The notebook itself has some figures displayed at the end which are very similar to those shown in figure 7 / 8 of the draft paper.

**Comment by ianhinder** [comment]
We now understand how to do this comparison, and will make a new issue for working out where the numbers from the draft paper came from.
