### ISSUE TITLE
Update deprecated GH action

### ISSUE THREAD

**Issue by SJaffa** [UoMResearchIT/mitsuba3-manchester#15]
`upload-artifact@v3` and `download-artifact@v3` need updating to v4

https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md

Used [here](https://github.com/UoMResearchIT/mitsuba3-manchester/blob/1689b5d2d702a28a45dbd8019b9e35b89f63cd1c/.github/workflows/wheels.yml#L94) and  [here](https://github.com/UoMResearchIT/mitsuba3-manchester/blob/1689b5d2d702a28a45dbd8019b9e35b89f63cd1c/.github/workflows/wheels.yml#L106)

**Comment by andrewgait** [comment]
This hasn't been updated on the main mitsuba3 repository yet, but I am happy to do that on this fork for now to reduce the amount of warnings that the UoMResearchIT organisation gets about this deprecation.
